#include "interrupts_signals.h"
#define INTERRUPT_REGISTER_CALLBACK(number) \
  interrupts_description_table_set_gate(number, (unsigned int)INTERRUPT_DEFINE_CALLBACK_NAME(number))
void interrupts_signals_register(void) {
  INTERRUPT_REGISTER_CALLBACK(0);
  INTERRUPT_REGISTER_CALLBACK(1);
  INTERRUPT_REGISTER_CALLBACK(2);
  INTERRUPT_REGISTER_CALLBACK(3);
  INTERRUPT_REGISTER_CALLBACK(4);
  INTERRUPT_REGISTER_CALLBACK(5);
  INTERRUPT_REGISTER_CALLBACK(6);
  INTERRUPT_REGISTER_CALLBACK(7);
  INTERRUPT_REGISTER_CALLBACK(8);
  INTERRUPT_REGISTER_CALLBACK(9);
  INTERRUPT_REGISTER_CALLBACK(10);
  INTERRUPT_REGISTER_CALLBACK(11);
  INTERRUPT_REGISTER_CALLBACK(12);
  INTERRUPT_REGISTER_CALLBACK(13);
  INTERRUPT_REGISTER_CALLBACK(14);
  INTERRUPT_REGISTER_CALLBACK(15);
  INTERRUPT_REGISTER_CALLBACK(16);
  INTERRUPT_REGISTER_CALLBACK(17);
  INTERRUPT_REGISTER_CALLBACK(18);
  INTERRUPT_REGISTER_CALLBACK(19);
  INTERRUPT_REGISTER_CALLBACK(20);
  INTERRUPT_REGISTER_CALLBACK(21);
  INTERRUPT_REGISTER_CALLBACK(22);
  INTERRUPT_REGISTER_CALLBACK(23);
  INTERRUPT_REGISTER_CALLBACK(24);
  INTERRUPT_REGISTER_CALLBACK(25);
  INTERRUPT_REGISTER_CALLBACK(26);
  INTERRUPT_REGISTER_CALLBACK(27);
  INTERRUPT_REGISTER_CALLBACK(28);
  INTERRUPT_REGISTER_CALLBACK(29);
  INTERRUPT_REGISTER_CALLBACK(30);
  INTERRUPT_REGISTER_CALLBACK(31);
}
void interrupts_signals_handler(s_asm_registers registers) {
  // interrupt has been received
}
